# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: "composite"
  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - name: action-interests-puller
    uses: Nikhilsunil90s/action-interest-puller@1.0.1
